tutorlab/tutorlab/forum/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'forum'
urlpatterns = [
    url(r'^$', views.forum, name='forum'),
    url(r'ajax-bookmark-post/$', views.bookmark_post, name='ajax_bookmark_post'),
    url(r'ajax-create-post/$', views.create_post, name='ajax_create_post'),
    url(r'ajax-create-comment/$', views.create_comment, name='ajax_create_comment'),
    url(r'ajax-flag-post/$', views.flag_post, name='ajax_flag_post'),
    url(r'ajax-forum-search/$', views.forum_search, name='ajax_forum_search'),
    url(r'ajax-increase-view-count/$', views.increase_view_count, name='ajax_increase_view_count'),
    url(r'ajax-vote-comment/$', views.vote_comment, name='ajax_vote_comment'),
    url(r'ajax-vote-post/$', views.vote_post, name='ajax_vote_post'),
    url(r'post/(?P<slug>[\w-]+)-(?P<id>\d+)/$', views.post_view, name='post_view'),
]

tutorlab/tutorlab/home/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^login/$', views.submit_login, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'schedule/$', views.ta_schedule, name='schedule'),
    url(r'^pusher_authenticate/$', views.pusher_authentication, name='auth'),
    url(r'^admin_import/$', views.admin_import, name='admin_import'),
    url(r'^admin_purge/$', views.admin_purge, name='admin_purge'),
    url(r'^admin_manage/$', views.admin_manage, name='admin_manage')
]

tutorlab/tutorlab/messenger/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name='messenger'
urlpatterns = [
    #url(r'^(?P<label>[\w-]{,50})/$', views.chat_room , name="msg"),
    
    url(r'^(?P<label>[A-z]{3}[0-9]{3})/$', views.gen_token , name="msg"),
    url(r'^(?P<token>[\w\-:]+)/$', views.chat_room, name="room"),
]

tutorlab/tutorlab/student/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'student'
urlpatterns = [
   url(r'^$', views.student, name='student'),
   url(r'activate-student/(?P<token>[\w:-]+)$', views.activateStudent, name='activate_student'),
   url(r'confirm-appt/$', views.confirmAppt, name='confirm_appt'),
   url(r'create-appt/$', views.createAppt, name='create_appt'),
   url(r'create-student/$', views.createStudent, name='create_student'),
   url(r'delete-appt/$', views.deleteAppt, name='delete_appt'),
   url(r'delete-event/$', views.deleteEvent, name='delete_event'),
   url(r'request-new-tutor/$', views.newTutor, name='new_tutor'),
   url(r'api/cancel-request/$', views.cancelRequest, name='cancel_request'),
   url(r'api/delete-survey/$', views.deleteSurvey, name='delete_survey'),
   url(r'api/get-classes/$', views.getClasses, name='get_classes'),
   url(r'api/get-issue-list/$', views.getIssues, name='get_issues'),
   url(r'api/post-request/$', views.postRequest, name='post_request'),
   url(r'api/submit-survey/$', views.submitSurvey, name='submit_survey'),
]
 

tutorlab/tutorlab/tutorlab/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^', include('home.urls')),
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^student/', include('student.urls')),
    url(r'^instructor/', include('instructor.urls')),
    url(r'^ta_tutor/',include('ta_tutor.urls')),
    url(r'^tutor_admin/', include('tutor_admin.urls')),
    url(r'^survey/', include('survey.urls')),
    url(r'^password_reset/',include('password_reset.urls')),
    url(r'^msg/',include('messenger.urls')),
    url(r'^forum/', include('forum.urls')),
]

#if settings.DEBUG:
#    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutorlab/tutorlab/home/models.py
from django.db import models

# Create your models here.
class App_Course(models.Model):
    course_name = models.CharField(max_length = 40)
    course_number = models.IntegerField(default = 0)
    course_section = models.IntegerField(default = 0)

    def __str__(self):
        return self.course_name

class CommonStudentIssue(models.Model):
    issue = models.CharField(max_length = 150)

    def __str__(self):
        return self.issue

tutorlab/tutorlab/student/models.py
from django.contrib.auth.models import User
from django.db import models

# create class model with relation to student


class Student(models.Model):
	student = models.OneToOneField(User, null=True)
	first_name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=30)
	abc123 = models.CharField(max_length=6)
	token = models.CharField(max_length=100, null=True)
	forum_flag_count = models.IntegerField(default=0)

	def __str__(self):
		return str(self.student)


class Queue(models.Model):
	abc123 = models.CharField(max_length = 6)
	whole_name = models.CharField(max_length = 30, null=True)
	chair = models.CharField(max_length = 12)
	className = models.CharField(max_length = 40, null=True)
	classID = models.CharField(max_length = 8)
	question =  models.CharField(max_length = 100, null=True)
	inSession = models.BooleanField(default=False)
	host = models.CharField(max_length=150, null=True)
	port = models.IntegerField(default=0)
	isChat = models.BooleanField(default=0)
	chat_token = models.CharField(max_length=150, null=True)
	def __str__(self):
		return self.abc123

tutorlab/tutorlab/student/forms.py
from django.forms import ModelForm, DateInput
from ta_tutor.models import ApptDate
from datetimewidget.widgets import DateTimeWidget
from django.forms.widgets import HiddenInput
from instructor.models import Student


class ApptDateForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ApptDateForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
        })
        self.fields['student'].widget = HiddenInput()
    class Meta:
        model = ApptDate
        fields = [
            'student',
            'course_number',
            'appt_date',
            'comments',
        ]
        dateTimeOptions = {
            'format': 'mm/dd/yyyy H:ii P',
            'showMeridian' : True
        }
        widgets = {
            'appt_date': DateTimeWidget(options = dateTimeOptions, attrs={'id':"appt_date"}, bootstrap_version=3),
        }

tutorlab/tutorlab/home/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from django.core.exceptions import ObjectDoesNotExist

from datetime import datetime
try:
    from django.contrib.sites.shortcuts import get_current_site
except ImportError:
    from django.contrib.sites.models import get_current_site
from django.core import signing
from django.core.files.storage import FileSystemStorage
from django.core.mail import send_mail
from django.core.validators import validate_email
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.template import loader
from django.views.decorators.csrf import csrf_exempt

from .models import App_Course
from instructor.models import Instructor, Course, Student
from tutor_admin.models import Term
from ta_tutor.models import Session
from survey.models import Survey
from student.models import Student as StudentAccount

from pusher import Pusher, pusher
import codecs, json, sys, pyexcel as pe
from collections import defaultdict
from xlrd import XLRDError

# LOAD HOME PAGE
def index(request):
    return render(request, 'home/home.html')

# CONTACT US PAGE
def contact(request):
    context = {
        'contact': ['Email: UtsaTutorLab@gmail.com'],
        'title': "Contact Us",
    }
    return render(request, 'home/contact.html', context)

# LOGIN USER, REDIRECT TO THEIR PROFILE
def submit_login(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            if user.groups.filter(name='Student').exists():
                return HttpResponse(
                    json.dumps("/student"),
                    content_type="application/json"
                )
            if user.groups.filter(name='Tutor').exists():
                return HttpResponse(
                    json.dumps("/ta_tutor"),
                    content_type="application/json"
                )
            if user.groups.filter(name='Tutor_Admin').exists():
                return HttpResponse(
                    json.dumps("/tutor_admin"),
                    content_type="application/json"
                )
            if user.groups.filter(name='Instructor').exists():
                return HttpResponse(
                    json.dumps("/instructor"),
                    content_type="application/json"
                )
            if username == 'admin' or username == 'bifrost_larry':
                return HttpResponse(
                    json.dumps("/admin"),
                    content_type="application/json"
                )
        else:
            return HttpResponse(
                json.dumps("false-1"),
                content_type="application/json"
            )
    else:
        return HttpResponse(
            json.dumps("false-2"),
            content_type="application/json"
        )

# LOGOUT USER
def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

# REDIRECT TO USER PROFILE
def profile(request):
    user = request.user
    if user is not None:
        if user.is_active:
            if user.groups.filter(name='Student').exists():
                return HttpResponseRedirect('/../student/')
            if user.groups.filter(name='Tutor').exists():
                return HttpResponseRedirect('/../ta_tutor/')
            if user.groups.filter(name='Instructor').exists():
                return HttpResponseRedirect('/../instructor/')
            if user.groups.filter(name='Tutor_Admin').exists():
                return HttpResponseRedirect('/../instructor/')
            if user.username == 'admin' or  user.username == 'bifrost_larry':
                return HttpResponseRedirect('/../admin/')
        else:
            return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/')

@csrf_exempt
def pusher_authentication(request):
	pusher_client = pusher.Pusher(app_id=settings.PUSHER_APP_ID,key=settings.PUSHER_KEY,secret=settings.PUSHER_SECRET)
	pusher_client.trigger(u'ch1',u'enqueue',{})	

	return HttpResponse("Ooh secret")

# SHOWS ALL TUTORS SCHEDULES
def ta_schedule(request):
    context = {
        'title': "Tutor Schedule",
    }
    return render(request, 'home/schedule.html', context)




@login_required(login_url='/admin/')
def admin_import(request):
    if request.user.is_active:
        if not request.user.is_superuser:
            return HttpResponseRedirect('/profile')
        if request.method == "GET":
            return render(request, "home/admin_import.html")
        if request.method == "POST" and request.FILES['file']:
            xlsFile = request.FILES['file']
            i_first_name = i_last_name = i_user_name = i_email = class_name = class_num = s_first_name = s_last_name = s_user_name = ' '
            num_i = num_c = num_s = 0
            try:
                fs = FileSystemStorage()
                filename = fs.save(xlsFile.name, xlsFile)
                print("File name =", xlsFile)
                sheet = pe.get_sheet(file_name=fs.path(xlsFile.name), name_columns_by_row=0)
                records = sheet.to_records()
                for record in records:
                    keys = sorted(record.keys())
                    for key in keys:
                        if key == "Instructor First Name":
                            print(str(record[key]))
                            i_first_name = record[key]
                        elif key == "Instructor Last Name": 
                            print(str(record[key]))
                            i_last_name = record[key]
                        elif key == "Instructor Username": 
                            print(str(record[key]))
                            i_user_name = record[key]
                        elif key == "Instructor Email":
                            print(str(record[key]))
                            i_email = record[key]
                        elif key == "Class Name":
                            print(str(record[key]))
                            class_name = record[key]
                        elif key == "Class Number":
                            print(str(record[key]))
                            class_num = record[key]
                        elif key == "Student abc123":
                            print(str(record[key]))
                            s_user_name = record[key]
                        elif key == "Student First Name":
                            print(str(record[key]))
                            s_first_name = record[key]
                        elif key == "Student Last Name":
                            print(str(record[key]))
                            s_last_name = record[key]

                    # Get or create user
                    user, user_created = User.objects.get_or_create(username=i_user_name, first_name=i_first_name, last_name=i_last_name, email=i_email)
                    group = Group.objects.get(name='Instructor')
                    group.user_set.add(user)
                    # Get or create current instructor
                    cur_instructor,created = Instructor.objects.get_or_create(user=user, first_name=i_first_name, last_name=i_last_name, email=i_email)
                    cur_instructor.save()

                    if(user_created):
                        # send email to setup password
                        send_activation(request, user.username, user.email)
                        num_i+=1

                    # Get or create current course and associate with instructor
                    cur_course, course_created = Course.objects.get_or_create(course_num=class_num, course_name=class_name)
                    cur_course.save()
                    cur_course.Instructor = cur_instructor
                    cur_course.save()
                    if(course_created):
                         num_c+=1                    
                    
                    # Get or create current student and associate with course
                    cur_student, student_created = Student.objects.get_or_create(first_name=s_first_name, last_name=s_last_name, studentID=s_user_name)
                    cur_student.save()
                    cur_student.courses.add(cur_course)
                    cur_student.save()
                    if(student_created):
                        num_s+=1
        
                fs.delete(xlsFile.name)
                data = {
                    "bool":"true",
		    "i_created":num_i,
                    "c_created":num_c,
                    "s_created":num_s
                }
                return HttpResponse(
                    json.dumps(data),
                    content_type="application/json"
                )


            except XLRDError:
                print("xlrd error")
                lastCol = firstCol = userCol = 0
                i_last_name = i_first_name = i_email = class_name = class_num = s_first_name = s_last_name = s_user_name = ""
                fs = FileSystemStorage()
                filename = fs.save(xlsFile.name, xlsFile)
                with codecs.open(fs.path(xlsFile.name), encoding='UTF-16') as f:
                    for rowx, row in enumerate(f):
                        if row.endswith(u'\r\n'): row = row[:-2]
                        data = row.split(u'\t ,')
                        for colx, datum in enumerate(data):
                            info = datum.strip("'\"")
                            if(rowx == 0):
                                if( info == 'Instructor First Name'):
                                    print(info)
                                    iFirstCol = colx

tutorlab/tutorlab/student/templates/student/activate_student.html
{% extends "home/base.html" %}
{% block page %}
<div class="jumbotron text-center" style="margin-top:50px">
  <h1>Welcome Student</h1> 
  <p>You have activated your account, now set your passoword</p>
</div>
<div class="panel panel-default" style="max-width:700px; margin: 40px auto 100px;">
  <div class="panel-heading">
    <h3 class="panel-title">Set Password</h3>
  </div>
  <form id="set-password-form" action="" method="POST">
    {% csrf_token %}
    <div class="panel-body">
        <div class="alert alert-danger" id="password-set-fail-alert" role="alert" style="display:none; margin-bottom:0px;"></div>
		<div class="alert alert-success" id="password-set-success-alert" role="alert" style="display:none; margin-bottom:0px;"></div>
        <label>Password</label>
        <input class="form-control" type="password" name="password" style="margin-bottom:5px;">
        <label>Confirm Password</label>
        <input class="form-control" type="password" name="confirm-password" style="margin-bottom:5px;">
        <button type="submit" class="btn btn-primary pull-right" onclick="activate_account()">submit</button>
    </div>
  </form>
</div>
{% endblock page %}

tutorlab/tutorlab/student/templates/student/appointment.html
{% extends "student/base.html" %}
{% load staticfiles %}
{% block page %}

{% block addHead %}
    {{ form.media }}
{% endblock addHead %}

{% block head_title %}
    <title>Appointments</title>
{% endblock head_title %}

<div class="row" id="student-appt-row" style="margin-left:35px">
    <div class="col-md-8">
        <div class="panel panel-default" style="margin-top:50px;">
            <div class="panel-heading">
                <h3 class="panel-title">Set up an appointment</h3>
            </div>
            <div class="panel-body">
                <div class="alert alert-danger" id="invalid-form" role="alert" style="display:none; margin-bottom: -10px;" >All fields are required</div>
                <div class="alert alert-success" id="success-form" role="alert" style="display:none; margin-bottom: -10px;" >Appointment Sent</div>
                <form id="create_appt" action="{% url 'student:create_appt' %}" method="post" class="post-form">
                    {% csrf_token %}
                    <div class="form-body">
                        <fieldset>
                            {% for field in form %}
                                {% if forloop.counter == 1 %}
                                    <div class="control-group">
                                        {% comment %}<label class="control-label" style="margin-top:20px">{{ field.label }}</label> {% endcomment %}
                                        <div class="controls">{{ field }}
                                            {% if field.help_text %}
                                                <p class="help-inline"><small>{{ field.help_text }}</small></p>
                                            {% endif %}
                                        </div>
                                    </div>
                                {% endif %}
                                {% if forloop.counter > 1 %}
                                    {% if field.errors %}
                                        <div class="control-group error">
                                            <label class="control-label" style="margin-top:20px">{{ field.label }}</label> 
                                            <div class="controls">{{ field }}
                                                <span class="help-inline">
                                                    {% for error in  field.errors %}{{ error }}{% endfor %}
                                                </span>
                                            </div>
                                        </div>
                                    {% else %}
                                        <div class="control-group">
                                            <label class="control-label" style="margin-top:20px">{{ field.label }}</label> 
                                            <div class="controls">{{ field }}
                                                {% if field.help_text %}
                                                    <p class="help-inline"><small>{{ field.help_text }}</small></p>
                                                {% endif %}
                                            </div>
                                        </div>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                        </fieldset>
                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary" style="margin-top:20px">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div><!-- end col-md-8 -->
    <div class="col-md-4">
        <div class="alert alert-success" id="appt-success-alert" role="alert" style="display:none; margin-bottom: -40px;"></div>
        <div class="alert alert-danger" id="appt-failed-alert" role="alert" style="display:none; margin-bottom: -40px;"></div>
        <div class="panel panel-default" style="margin-top:50px;">
            <div class="panel-heading">
                <h3 class="panel-title">Requested Appointments</h3>
            </div>
             <div class="panel-body">
                 <div class="panel-group" id="studentAccordion" role="tablist" aria-multiselectable="true">
                  {% for appt in appts %}
                    <div class="panel panel-default">
                      <div class="panel-heading" role="tab" id="headingOne">
                        <h4 class="panel-title">
                          <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#{{ appt.pk }}" aria-expanded="true" aria-controls="collapseOne">
                            {{appt.course_number }}
                          </a>
                        </h4>
                      </div>
                      <div id="{{ appt.pk }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                        {% csrf_token %}
                        <div class="panel-body">
                          {% if appt.student_approved == True and appt.tutor_approved == True %}
                            <p> Appointment Date - {{ appt.appt_date }} </p>
                            <p> Comments: {{ appt.comments }}</p>
                            <h5>Appointment Approved!</h5>
                            <p>Your tutor is {{appt.tutor.tutor.first_name}} {{appt.tutor.tutor.last_name}}</p>
                            <button type="button" class="btn btn-danger" onclick="show_delete_event_modal({{appt.id}})">Cancel Appointment</button>
                          {% elif appt.student_approved == False and appt.tutor_approved == True %}
                            <p> Appointment Date - {{ appt.old_appt_date }} </p>
                            <p> Comments: {{ appt.comments }}</p>
                            <h5>Your tutor needs to change your appointment date</h5>
                            <p>New date: {{ appt.appt_date }}</p>
                            <p>Would you like to confirm this date, request a new date or request a different tutor?</p>
                            <button type="button" class="btn btn-primary" onclick="confirm_date({{appt.id}})">Confirm Date</button>
                            <button type="button" class="btn btn-primary" onclick="request_new_tutor({{appt.id}})">Request New Tutor</button>
                          {% else %}
                            <p> Appointment Date - {{ appt.appt_date }} </p>
                            <p> Comments: {{ appt.comments }}</p>
                            <h5>Waiting approval...</h5>
                            <button type="button" class="btn btn-danger" onclick="show_delete_appt_modal({{appt.id}})">Cancel Request</button>
                          {% endif %}
                        </div>
                      </div>
                    </div>
                  {% endfor %}
                </div>
            </div>
        </div>
    </div><!-- end col-md-4 -->
</div><!-- end row -->
{% endblock page %}

tutorlab/tutorlab/student/templates/student/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
 <link rel="icon" src="{% static 'img/tutorlab_logo2.png' %}">

    {% block head_title %} 
        <title>Welcome {{ student_info.student.first_name }}</title>
    {% endblock head_title %}
    
<!-- Bootstrap core CSS -->
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<!-- Side-nav .js -->
    <script src="{% static 'js/personal.js' %}"></script>

<!-- PUSHER JS -->
	{% load pusherable_tags %}
	<script src="https://js.pusher.com/3.2/pusher.min.js"></script>
    <script src="{% static 'js/queue.js' %}"></script>
      
<!-- FullCalendar .js .css -->
    <link rel='stylesheet' href="{% static 'fullcalendar/fullcalendar.css' %}" />
    <script src="{% static 'fullcalendar/lib/moment.min.js' %}"></script>
    <script src="{% static 'fullcalendar/fullcalendar.js' %}"></script>
    <link href="/static/css/datetimepicker.css" type="text/css" media="all" rel="stylesheet"/>
    <script type="text/javascript" src="/static/js/bootstrap-datetimepicker.js"></script>
      
<!-- Custom styles for this template -->
    <link href="{% static 'css/personal.css' %}" rel="stylesheet">
    <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">


    {% block addHead %} {% endblock addHead%}

  </head>
<!-- ================================================== -->
  <body>
      
<!--HEADER NAVBAR-->
    {% block header %}
        {% include "home/includes/header.html" %}
    {% endblock header %}

    <!-- STUDENT MODALS -->
	{% block modal %}
        {% include "student/includes/modal.html" %}
	{% endblock modal %}
     
<!-- SIDE NAV BAR -->
<div class="container" style="margin-top:60px;">
    <ul id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="openbtn" onclick="openNav()">&#9776;</a>
        <!--<h2 class="title">Menu</h2>-->
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a href="{% url 'home:profile' %}" style="padding-left:13px;"><span class="glyphicon glyphicon-home" aria-hidden="true" style="padding-right:17px"></span>Notifications</a>
        <a href="{% url 'student:create_appt' %}"><span class="glyphicon glyphicon-calendar" aria-hidden="true" style="padding-right:15px"></span>Appointment</a>
        <a href="{% url 'messenger:msg' label=request.user.username %}"><span class="glyphicon glyphicon-comment" aria-hidden="true" style="padding-right:15px"></span>Chat With Tutor</a>
        <a href="{% url 'forum:forum' %}"><span class="glyphicon glyphicon-edit" aria-hidden="true" style="padding-right:15px"></span>Forum</a>
        <a href="#"><span class="glyphicon glyphicon-option-vertical" aria-hidden="true" style="padding-right:15px"></span>More Later</a>
    </ul>

<!--PAGE CONTENT-->
    {% block page %}

    {% endblock page %}
</div>

<!--FOOTER BAR-->
<!--
    {% block footer %}
      {% include "home/includes/footer.html" %}
    {% endblock %}  
-->

<!-- Bootstrap core JavaScript
================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% comment %}<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>{% endcomment %}
<!--================================================== -->
    </body>
</html>

tutorlab/tutorlab/student/templates/student/newuser.html
{% extends "home/base.html" %}
{% load staticfiles %}
{% block page %}
<!-- Create Account Form -->
  <div class="container-fluid" align-self:center; style="margin-top: 100px;">
    <div class="panel panel-default" style="background-color:lightgrey">
        <div class="panel-heading">
            <h3 class="panel-title" style="text-align: center">Create New Student Account</h3>
        </div>
        <div class="panel-body">
          <div class="alert alert-danger col-xs-12 col-md-offset-3 col-md-6" id="create-student-fail-alert" role="alert" style="display:none; margin-bottom:0px;"></div>
		      <div class="alert alert-success col-xs-12 col-md-offset-3 col-md-6" id="create-student-success-alert" role="alert" style="display:none; margin-bottom:0px;"></div>
          <form id="create-student-form" action="{% url 'student:create_student' %}" method="POST">{% csrf_token %}
            <div class="row" style="padding-bottom: 10px;">
              <div class="col-xs-12 col-md-offset-3 col-md-6">
                <input type="text" placeholder="First Name" name="first" class="form-control">
              </div>
            </div>
            <div class="row" style="padding-bottom: 10px;">
              <div class="col-xs-12 col-md-offset-3 col-md-6">
                <input type="text" placeholder="Last Name" name="last" class="form-control">
              </div>
            </div>
            <div class="row" style="padding-bottom: 10px;">
              <div class="col-xs-12 col-md-offset-3 col-md-6">
                <input type="text" placeholder="Student abc123" name="abc123" class="form-control">
              </div>
            </div>
            {% comment %}<div class="row" style="padding-bottom: 10px;">
              <div class="col-xs-12 col-md-offset-3 col-md-6">
                <input type="password" placeholder="Password" name="password" class="form-control">
              </div>
            </div>{% endcomment %}
            <div class="row">
              <div class="col-xs-12 col-md-offset-3 col-md-6" style="padding-bottom: 10px;">
                <input type="text" placeholder="Prefered Email" name="email" class="form-control">
              </div>
              <div class="col-xs-12">
                <p style="text-align: center">* We would appreciate you completing a short survey we send to your email to help let us know how the tutors are doing</p>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12 col-md-offset-3 col-md-6">
                <button class="btn btn-success pull-right" type="submit" id="create-student-btn">Submit</button>
              </div>
            </div>
          </form>
        </div>
    </div>
  </div>
{% endblock page %}