tutorlab/tutorlab/home/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^login/$', views.submit_login, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'schedule/$', views.ta_schedule, name='schedule'),
    url(r'^pusher_authenticate/$', views.pusher_authentication, name='auth'),
    url(r'^admin_import/$', views.admin_import, name='admin_import'),
    url(r'^admin_purge/$', views.admin_purge, name='admin_purge'),
    url(r'^admin_manage/$', views.admin_manage, name='admin_manage')
]

tutorlab/tutorlab/ta_tutor/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'ta_tutor'
urlpatterns = [
    url(r'^$', views.ta_tutor, name='ta_tutor'),
    url(r'activate-tutor/(?P<token>[\w:-]+)/$', views.activate_account, name='activate_account'),
    url(r'add-event/$', views.add_event, name='add_appt'),
    url(r'delete-event/$', views.delete_event, name='delete_appt'),
    url(r'delete-notification/$', views.delete_notification, name='delete_notification'),
    url(r'get-events/$', views.get_events, name='get_appts'),
    url(r'send-date/$', views.send_date, name='send_date'),
    url(r'^session/$', views.inSession, name='inSession'), 
    url(r'start-session/$', views.startSession, name='start_session'),
    url(r'viewed/$', views.viewed_notifications, name='viewed'), 
]

tutorlab/tutorlab/tutorlab/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^', include('home.urls')),
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^student/', include('student.urls')),
    url(r'^instructor/', include('instructor.urls')),
    url(r'^ta_tutor/',include('ta_tutor.urls')),
    url(r'^tutor_admin/', include('tutor_admin.urls')),
    url(r'^survey/', include('survey.urls')),
    url(r'^password_reset/',include('password_reset.urls')),
    url(r'^msg/',include('messenger.urls')),
    url(r'^forum/', include('forum.urls')),
]

#if settings.DEBUG:
#    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutorlab/tutorlab/ta_tutor/models.py
from django.contrib.auth.models import User
from django.db import models
from student.models import Student

class Tutor(models.Model):
    TUTOR_TYPES = (
        ('CS', 'CS'),
        ('MATLAB', 'MATLAB'),
        ('BOTH', 'BOTH')
    )

    tutor = models.OneToOneField(User, on_delete=models.CASCADE, null=True, limit_choices_to={'groups__name':'TA/Tutors'})
    name = models.CharField(max_length=30, null=True)
    profile_image = models.ImageField(null=True, blank=True)
    classification = models.CharField(max_length=10, default='Freshman')
    about_me = models.TextField(blank=True)
    tutor_type = models.CharField(max_length=6, default='CS', choices=TUTOR_TYPES)
    avg_survey_score = models.DecimalField(max_digits=4, decimal_places=2, default=0)
    survey_count = models.IntegerField(default=0)
    token = models.CharField(max_length=150, null=True)

    @classmethod
    def create(cls, user):
        tutor = cls(tutor=user)
        return tutor

    def __str__(self):
        return str(self.tutor.get_full_name())
    
class Session(models.Model):    
    tutor = models.ForeignKey(Tutor, null=True)
    sessionID = models.DateTimeField(auto_now=False, auto_now_add=True, null=True) #this will set datetime when updated
    student = models.CharField(max_length=6)    
    whole_name = models.CharField(max_length=30, null=True)
    classID = models.CharField(max_length = 40)    
    duration = models.DurationField(max_length=6)    
    notes = models.TextField(help_text='Take detailed notes as you help out.')    
    def __str__(self):        
        return str(self.tutor)

class Notification(models.Model):
    tutor = models.ForeignKey(Tutor, on_delete=models.CASCADE, null=True)
    send_date = models.DateTimeField(auto_now=False, auto_now_add=True)
    message_title = models.CharField(max_length=100)
    message_content = models.CharField(max_length=2000)
    viewed = models.BooleanField(default=False)
    
    @classmethod
    def create(cls, user):
        tutor = cls(tutor=user)
        return tutor

    def __str__(self):
        return self.message_title

class Event(models.Model):
    tutor = models.ForeignKey(Tutor, on_delete=models.CASCADE, null=True)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=True)
    start = models.CharField(max_length=50)
    end = models.CharField(max_length=50)
    course = models.CharField(max_length = 40)
    description = models.CharField(max_length=500)
    confirmed = models.BooleanField(default=True)

    @classmethod
    def create(cls, user):
        tutor = cls(tutor=user)
        return tutor

    def __str__(self):
        return str(self.student)
    
class ApptDate(models.Model):
    tutor = models.ForeignKey(Tutor, on_delete=models.CASCADE, null=True)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, null=True)    
    course_number = models.CharField(max_length = 40)
    appt_date = models.CharField(max_length=50)
    old_appt_date = models.CharField(max_length=50, null=True)
    comments = models.CharField(max_length=500)
    student_approved = models.BooleanField(default=True)
    tutor_approved = models.BooleanField(default=False)
    def __str__(self):
        return str(self.student) + " " + self.course_number

tutorlab/tutorlab/ta_tutor/forms.py
from django.forms import Form, ModelForm, Textarea
from .models import Session, Tutor, ApptDate
from datetimewidget.widgets import DateTimeWidget

class SessionForm(ModelForm):
    class Meta:
        model = Session
        fields = ['student', 'whole_name', 'classID', 'duration', 'notes']
        widgets = {'notes': Textarea(attrs={'cols':200, 'rows':10})}

tutorlab/tutorlab/ta_tutor/views.py
from django.conf import settings 
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.core import signing
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
from django.forms.formsets import formset_factory
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.template.context_processors import csrf
try:
    from django.contrib.sites.shortcuts import get_current_site
except ImportError:
    from django.contrib.sites.models import get_current_site
from pusher import pusher
from .forms import SessionForm
from .models import Tutor, ApptDate, Notification, Event
from student.models import Student, Queue
from survey.models import Survey
from home.models import App_Course
from collections import OrderedDict
import json

# Initialize pusher
pusher_client = pusher.Pusher(app_id=settings.PUSHER_APP_ID,
                    key=settings.PUSHER_KEY,
                    secret=settings.PUSHER_SECRET)

# TUTOR HOME PAGE INFO
def ta_tutor(request):
    if request.user.is_active:
        tutor = get_object_or_404(Tutor, tutor=request.user)
        student_queue = Queue.objects.order_by('id')
        student_list = Student.objects.order_by('id')
        course_list = App_Course.objects.all()
        requested_appts = ApptDate.objects.filter(tutor_approved = False).order_by('pk')
        request_num = requested_appts.count()
        notifications = Notification.objects.filter(tutor = tutor).order_by('-send_date')
        notification_num = notifications.filter(viewed=False).count()
    
        context = {
            'requested_appts':requested_appts,
            'request_num':request_num,
            'notifications':notifications,
            'notification_num':notification_num,
            'student_queue':student_queue,
            'tutor_info':tutor,
            'student_list':student_list,
            'course_list':course_list,
        }
        if not request.user.groups.filter(name='Tutor').exists():
            messages.error(request, "You do not have access to this page")
            return HttpResponseRedirect('/')
        return render(request, 'ta_tutor/home.html', context)
    else:
        messages.error(request, "You must login to see this page")
        return HttpResponseRedirect('/')

# ACTIVATE TUTOR ACCOUNT
def activate_account(request, token):
    try:
        abc123 = signing.loads(token,
                        max_age=(3600 * 24) * 7, #expires in one week
                        salt=settings.SECRET_KEY)
        user = get_object_or_404(User, username=abc123)
        if not user.tutor.token == token:
            raise Http404("Your token is not valid")
        if request.method == 'POST':
            pass1 = request.POST.get('password')
            pass2 = request.POST.get('confirm-password')
            if len(pass1) < 8:
                return HttpResponse(
                    json.dumps("fail1"),
                    content_type="application/json"
                )
            elif pass1 != pass2:
                return HttpResponse(
                    json.dumps("fail2"),
                    content_type="application/json"
                )
            else:
                user = User.objects.get(username=abc123)
                user.set_password(pass1)
                user.is_active=True
                user.save()
                user = authenticate(username=abc123, password=pass1)
                if user is not None:
                    if user.is_active:
                        login(request, user)
                        user.tutor.token = None
                        user.tutor.save()
                        return HttpResponse(
                            json.dumps("/ta_tutor"),
                            content_type="application/json"
                        )
        else:
            return render(request, 'ta_tutor/activate_account.html')
    except signing.BadSignature:
        raise Http404("Invalid token")

# GET ALL CALENDAR EVENTS FOR THIS TUTOR
def get_events(request):
    if request.method == 'GET':
        tutor = get_object_or_404(Tutor, tutor=request.user)
        calendar_events = Event.objects.filter(tutor = tutor).order_by('pk')
        #create calendar jason array from events model
        events = []
        for event in calendar_events:
            temp = OrderedDict()
            temp['id'] = event.id
            temp['title'] = event.student.student.username
            temp['student'] = event.student.student.first_name + " " + event.student.student.last_name
            temp['start'] = event.start
            temp['end'] = event.end
            temp['description'] = event.description
            temp['confirmed'] = event.confirmed
            temp['course'] = event.course
            events.append(temp)
        return HttpResponse(
            json.dumps(events),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps('This is only a \'GET\' API')
        )

# ADD REQUEST TO CALENDAR AS AN EVENT
def add_event(request):
    if request.method == 'POST':
        appt_pk = request.POST.get('appt_pk')
        appt = ApptDate.objects.get(pk=appt_pk)
        tutor = get_object_or_404(Tutor, tutor=request.user)
        event = Event.create(tutor)
        event.student = appt.student
        event.start = appt.appt_date
        event.course = appt.course_number
        event.description = appt.comments
        event.save()
        appt.event = event
        appt.tutor = tutor
        appt.tutor_approved = True
        appt.save()
        pusher_client.trigger(u'appt', u'new',{})
        return HttpResponse(
            json.dumps('appt added'),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps('appt was not added'),
            content_type="application/json"
        )

# DELETE EVENT FROM CALENDAR
def delete_event(request):
    if request.method == 'POST':
        delete_id = request.POST.get('deleted_appt')
        event = Event.objects.get(id=delete_id)
        appt = ApptDate.objects.get(event=event)
        appt.delete()
        event.delete()
        pusher_client.trigger(u'appt', u'new',{})
        return HttpResponse(
            json.dumps("true"),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps("false"),
            content_type="application/json"
        )

# SEND NEW DATE BACK TO STUDENT
def send_date(request):
    if request.method == 'POST':
        event_id = request.POST.get('event_ID')
        new_date = request.POST.get('appt_date')
        if not new_date:
            return HttpResponse(
                json.dumps("false"),
                content_type="application/json"
            )
        else:
            event = get_object_or_404(Event, id=event_id)
            return_appt = get_object_or_404(ApptDate, event=event)
            event.start = new_date
            event.confirmed = False
            event.save()
            return_appt.old_appt_date = return_appt.appt_date
            return_appt.appt_date = new_date
            return_appt.student_approved = False
            return_appt.tutor_approved = True
            return_appt.save()
            pusher_client.trigger(u'appt', u'new',{})
            return HttpResponse(
                json.dumps(str(event_id) + " " + str(new_date)),
                content_type="application/json"
            )

# STARTS TUTORING SESSION
def startSession(request):
    studentName = request.POST.get('session-student-name')
    studentID = request.POST.get('studentID')
    classID = request.POST.get('class')
    tutor = get_object_or_404(Tutor, tutor=request.user)
    data = {
            'whole_name': studentName,
            'student': studentID,
            'classID': classID,
            'duration': '0',
            'notes':'',
            }
    form = SessionForm(data)
    form.fields['whole_name'].widget.attrs.update({'readonly':True, 'style':'border:0px'})
    form.fields['student'].widget.attrs.update({'readonly':True, 'style':'border:0px'})
    form.fields['classID'].widget.attrs.update({'readonly':True, 'style':'border:0px'})
    form.fields['duration'].widget.attrs.update({'readonly':True, 'style':'border:0px'})
    
    if request.user.is_active:
        if not request.user.groups.filter(name='Tutor').exists():
            messages.error(request, "You do not have access to this page")
            return HttpResponseRedirect('/')
        #pusher_client.trigger(u'ch1',u'enqueue',{u'data':'in session'})
        try:
            #if student is in queue list
            cur_stud = Queue.objects.get(abc123=studentID)
            # if student isn't in a session, set to True
            if cur_stud.inSession is False:
                cur_stud.inSession = True
                cur_stud.save()
                pusher_client.trigger(u'ch1',u'enqueue',{u'data':'in session'})
                return render(request, 'ta_tutor/session.html', {'studentName':studentName, 'studentID': studentID, 'classID': classID, 'form':form})
            #if student is in a session, just refresh page
            #elif cur_stud.inSession is True:
                #cur_stud.delete()
                
        except ObjectDoesNotExist:
            return render(request, 'ta_tutor/session.html', {'studentName':studentName, 'studentID': studentID, 'classID': classID, 'form':form})
        
        return HttpResponseRedirect('../')
    else:
        messages.error(request, "You must login to see this page")
        return HttpResponseRedirect('../')
    
# INSIDE TUTOR SESSION
def inSession(request):
    studentID = request.POST.get('student')
    tutor = get_object_or_404(Tutor, tutor=request.user)
    

tutorlab/tutorlab/ta_tutor/templates/ta_tutor/includes/modal.html
{% block modal %} 
{% if tutor_info.first_login %}
<!-- Tutor First Login modal -->
<div class="modal fade" id="firstLogin">
	<div class="modal-dialog modal-md">
		<div class="modal-content">
			<div class="modal-header">
				<a class="close" data-dismiss="modal">×</a>
				<h3>Welcome to TutorLab!</h3>
			</div>
			<div class="modal-body">
				<p>
                    We see that this is your first time logging in. Lets change your password to a better one!
                    Click the button below to change your password now.
                </p>
			</div>
			<div class="modal-footer">
				<a href="#" class="btn btn-primary">Change password</a>
			</div>
		</div>
	</div>
</div>
{% endif %}

<!-- Calendar Event Clicked Modal -->
<div id="calendarModal" class="modal fade">
	<div class="modal-dialog modal-md">
		<div class="modal-content">
			<form action="{% url 'ta_tutor:start_session' %}" method='post'>
				{% csrf_token %}
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span> <span class="sr-only">close</span></button>
					<h3>Appointment</h3>
				</div>
				<div class="modal-body"> 
					<div class="modal-inline">
						<h4>Student: </h4>
						<p id="modalabc123"></p>
						<input type="hidden" id="student" name="student">
						<p> - </p>
						<p id="modalStudent"></p>
					</div>
					<div class="modal-inline">
						<h4>Course: </h4>
						<p id="modalCourse"></p>
						<input type="hidden" id="classID" name="classID">
					</div>
					<div class="modal-inline">
						<h4>Date: </h4>
						<p id="modalDate"></p>
					</div>
					<div class="modal-inline">
						<h4>Description: </h4>
						<p id="modalDescription"></p> 
					</div>
					<div class="modal-inline">
						<h4>Student Confirmation: </h4>
						<p id="modalConfirmed"></p> 
					</div>
					<div class="modal-inline">
						<input type="hidden" id="modalID">
					</div>
				</div>
				<div class="modal-footer">
					<button type="submit" id="start-session-btn" class="btn btn-primary pull-left" onclick="start_session()">Start Appointment</button>
					<button type="button" id="change-date-btn" class="btn btn-primary" data-dismiss="modal" onclick="change_date()">Change Date</button>
					<button type="button" id="delete-event-btn" class="btn btn-danger" data-dismiss="modal" data-toggle="modal" data-target="#are_you_sure">Delete Appointment</button>
				</div>
			</form>
		</div>
	</div>
</div>

<!-- Change Appt Date Modal -->
<div class="modal fade" id="request_new_date">
	<div class="modal-dialog modal-md">
		<div class="modal-content">
			<form id="send_date" action="send-date/" method="POST">
			{% csrf_token %}
			<div class="modal-header">
				<a class="close" data-dismiss="modal">×</a>
				<h3>Send a new date</h3>
			</div>
			<div class="modal-body" id="date-modal-body">
				<div class="alert alert-danger" id="appt-send-failed-alert" role="alert" style="display:none;">You must enter a date</div>
				<div class="alert alert-success" id="appt-send-success-alert" role="alert" style="display:none;">New date sent</div>
				<div class="control-group">
					<div class="modal-inline">
						<h4>Old Date: </h4>
						<p id="modalOldDate"></p>
					</div>
					<input type="hidden" id="event_ID" name="event_ID">
					<label class="control-label">Appt date</label> 
					<div class="controls">
						<div id="appt_date" class="input-group date">
							<input class="form-control" id="new_appt_date" maxlength="50" name="appt_date" type="text" required />
							<span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
							<span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
						</div>
						<script type="text/javascript">
							$("#appt_date").datetimepicker({format: 'mm/dd/yyyy H:ii P',
								showMeridian: true,
								autoclose: true}).find('input').addClass("form-control");
						</script>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<div class="form-actions">
					<input type="submit" class="btn btn-primary" id="send_btn"></input>
				</div>
			</div>
			</form>
		</div>
	</div>
</div>

<!-- Are You Sure Delete Modal -->
<div class="modal fade" id="are_you_sure">
	<div class="modal-dialog modal-md">
		<div class="modal-content">
			<div class="modal-header">
				<a class="close" data-dismiss="modal">×</a>
				<h3>Are you sure you want to delete this Appointment?</h3>
			</div>
			<div class="modal-body">
				<button type="submit" class="btn btn-primary" style="margig:20px" data-dismiss="modal">Keep Appointment</button>
				<button type="submit" id="delete-event" class="btn btn-danger pull-right" data-dismiss="modal" onclick="delete_event()">Delete Appointment</button>
			</div>
		</div>
	</div>
</div>
{% endblock modal %}

tutorlab/tutorlab/ta_tutor/templates/ta_tutor/includes/timer.html
{% block timer %}
<script type="text/javascript">
	var c=0;
	var t;
	var timer_is_on=0;

	function timedCount()
	{
	document.getElementById('id_duration').value = c;
	c=c+1;
	t=setTimeout("timedCount()",1000);
	}

	function doTimer()
	{
	if (!timer_is_on)
 	 {
 	 timer_is_on=1;
 	 timedCount();
 	 }
	}

	function stopCount()
	{
	clearTimeout(t);
	timer_is_on=0;
	}

	function nl2br()
	{
		document.getElementById('id_notes').value = document.getElementById('id_notes').value.replace(/(\r\n|\n|\r)/gm,"");
	}
	

	window.onload = doTimer;
</script>
{% endblock timer%}