tutorlab/tutorlab/home/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^login/$', views.submit_login, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'schedule/$', views.ta_schedule, name='schedule'),
    url(r'^pusher_authenticate/$', views.pusher_authentication, name='auth'),
    url(r'^admin_import/$', views.admin_import, name='admin_import'),
    url(r'^admin_purge/$', views.admin_purge, name='admin_purge'),
    url(r'^admin_manage/$', views.admin_manage, name='admin_manage')
]

tutorlab/tutorlab/messenger/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name='messenger'
urlpatterns = [
    #url(r'^(?P<label>[\w-]{,50})/$', views.chat_room , name="msg"),
    
    url(r'^(?P<label>[A-z]{3}[0-9]{3})/$', views.gen_token , name="msg"),
    url(r'^(?P<token>[\w\-:]+)/$', views.chat_room, name="room"),
]

tutorlab/tutorlab/student/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'student'
urlpatterns = [
   url(r'^$', views.student, name='student'),
   url(r'activate-student/(?P<token>[\w:-]+)$', views.activateStudent, name='activate_student'),
   url(r'confirm-appt/$', views.confirmAppt, name='confirm_appt'),
   url(r'create-appt/$', views.createAppt, name='create_appt'),
   url(r'create-student/$', views.createStudent, name='create_student'),
   url(r'delete-appt/$', views.deleteAppt, name='delete_appt'),
   url(r'delete-event/$', views.deleteEvent, name='delete_event'),
   url(r'request-new-tutor/$', views.newTutor, name='new_tutor'),
   url(r'api/cancel-request/$', views.cancelRequest, name='cancel_request'),
   url(r'api/delete-survey/$', views.deleteSurvey, name='delete_survey'),
   url(r'api/get-classes/$', views.getClasses, name='get_classes'),
   url(r'api/get-issue-list/$', views.getIssues, name='get_issues'),
   url(r'api/post-request/$', views.postRequest, name='post_request'),
   url(r'api/submit-survey/$', views.submitSurvey, name='submit_survey'),
]
 

tutorlab/tutorlab/ta_tutor/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'ta_tutor'
urlpatterns = [
    url(r'^$', views.ta_tutor, name='ta_tutor'),
    url(r'activate-tutor/(?P<token>[\w:-]+)/$', views.activate_account, name='activate_account'),
    url(r'add-event/$', views.add_event, name='add_appt'),
    url(r'delete-event/$', views.delete_event, name='delete_appt'),
    url(r'delete-notification/$', views.delete_notification, name='delete_notification'),
    url(r'get-events/$', views.get_events, name='get_appts'),
    url(r'send-date/$', views.send_date, name='send_date'),
    url(r'^session/$', views.inSession, name='inSession'), 
    url(r'start-session/$', views.startSession, name='start_session'),
    url(r'viewed/$', views.viewed_notifications, name='viewed'), 
]

tutorlab/tutorlab/tutorlab/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^', include('home.urls')),
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^student/', include('student.urls')),
    url(r'^instructor/', include('instructor.urls')),
    url(r'^ta_tutor/',include('ta_tutor.urls')),
    url(r'^tutor_admin/', include('tutor_admin.urls')),
    url(r'^survey/', include('survey.urls')),
    url(r'^password_reset/',include('password_reset.urls')),
    url(r'^msg/',include('messenger.urls')),
    url(r'^forum/', include('forum.urls')),
]

#if settings.DEBUG:
#    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutorlab/tutorlab/messenger/models.py
from django.db import models
from django.utils import timezone

class Room(models.Model):
	name=models.TextField()
	label=models.SlugField(unique=True)
	studentConnected=models.BooleanField(default=False)
	tutorConnected=models.BooleanField(default=False)
	token = models.CharField(max_length=150, null=True)

	def __unicode__(self):
		return self.label

class Message(models.Model):
	room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='messages')
	handle = models.TextField()
	message = models.TextField()
	timestamp = models.DateTimeField(default=timezone.now, db_index=True)

	def __unicode__(self):
		return '[{timestamp}] {handle}: {message}'.format(**self.as_dict())

	@property
	def formatted_timestamp(self):
		return self.timestamp.strftime('%b %-d %-I:%M %p')

	def as_dict(self):
		return {'handle': self.handle, 'message': self.message, 'timestamp': self.formatted_timestamp}

    

tutorlab/tutorlab/messenger/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from django.db import IntegrityError
from django.views.generic.detail import DetailView
from .models import Room, Message
from ta_tutor.models import Tutor
from django.conf import settings 
from django.core import signing
from student.models import Queue
from survey.models import Survey
from pusher import pusher

#def chat_room(request, label):
def chat_room(request, token):
	# If the room with the given label doesn't exist, automatically create it upon first visit.
	# room, created = Room.objects.get_or_create(label=label)
	try:
		room_id = signing.loads(token,
                            max_age = settings.ROOM_TOKEN_EXPIRES,
                            salt=settings.SECRET_KEY)
	except signing.BadSignature:
		return HttpResponse("Incorrect signature")
	else:
		try:
			room = Room.objects.get(id=room_id)
		except ObjectDoesNotExist:
			return HttpResponse("Room doesn't exist")
		if room.token != token:
			return HttpResponse("Request already being handled")
	
	# We want to show the last 50 messages, orded by most-recent-last
	messages = reversed(room.messages.order_by('-timestamp')[:50])

	#Pusher Client Initialization
	pusher_client = pusher.Pusher(app_id=settings.PUSHER_APP_ID,
									key=settings.PUSHER_KEY,
									secret=settings.PUSHER_SECRET)

	# Let template know if user is a tutor
	isTutor = False
	# student = Queue.objects.create(abc123="000000",chair="00",classID="0000.00",inSession=True,)
	# tutor = Tutor.objects.create(name="000000")
	# student = None
	# tutor = None

	if request.user.groups.filter(name='Student'):
		whole_name = ""
		try:
			whole_name = str(request.user.get_full_name())
		except:
			whole_name = request.user

		try:
			# Create new Queue object
			Queue.objects.create(abc123=request.user, inSession=0, classID=0, chair=000, isChat=1, chat_token=token)
		except IntegrityError as err:
			print("THIS IS THE ERROR" + str(err))

		student = Queue.objects.get(abc123=request.user)
		student.whole_name = whole_name
		student.save()
		
		# Update tutor page queue
		pusher_client.trigger(u'ch1', u'enqueue', {u'label': request.user.username})

	if request.user.groups.filter(name="Tutor"):
		isTutor = True
		try:
			room = Room.objects.get(token=token)
			student = Queue.objects.get(abc123=room.label)
			student.inSession = 1
			student.save()
			pusher_client.trigger(u'ch1', u'enqueue', {})
			
		except ObjectDoesNotExist:
			return HttpResponseRedirect('../../ta_tutor')

	
		
	return render(request, "messenger/msg.html", {'room': room, 'messages': messages, 'isTutor':isTutor})

# give url a token for security

def gen_token(request, label):

	room = Room.objects.create(label=label)

	token = signing.dumps(room.id, salt=settings.SECRET_KEY)
	room.token = token
	room.save()

	try:
		# Create new Queue object
		student = Queue(abc123=request.user, inSession=0, classID=0, chair=000, isChat=1, chat_token=token )
		student.save()
	except IntegrityError:
		pass
	else:
		#Pusher Client Initialization
		pusher_client = pusher.Pusher(app_id=settings.PUSHER_APP_ID,
										key=settings.PUSHER_KEY,
										secret=settings.PUSHER_SECRET)
		pusher_client.trigger(u'ch1', u'enqueue', {u'label': request.user.username})

	return HttpResponseRedirect("../"+token)

	# return HttpResponse("Okay")

	# return render(request, "messenger/msg.html", {'token':token})
	# chat_room(request, token)

tutorlab/tutorlab/messenger/templates/messenger/base.html
{% load staticfiles %} 
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
<!--    <link rel="icon" href="../../favicon.ico">-->

    <title>{% block head_title %}Tutor Chat{% endblock head_title %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/personal.css' %}" rel="stylesheet">
  </head>
<!-- ================================================== -->
  <body style="background-color:#05101f">
    <!--<body style="background-color:white">-->
      
<!--HEADER NAVBAR-->
    {% block header %}
        {% include "home/includes/header.html" %}
    {% endblock %} 

<!--STUDENT MODALS-->
    {% block modal %}
      {% include "home/includes/modal.html" %}
    {% endblock %}

<!--PAGE CONTENT-->
    {% block page %}
      
    {% endblock %}

<!--FOOTER BAR-->
    <!--{% block footer %}
      {% include "home/includes/footer.html" %}
    {% endblock %}  -->

<!-- Bootstrap core JavaScript
================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
<!--================================================== -->
</html>

tutorlab/tutorlab/messenger/templates/messenger/msg.html
{% extends "messenger/base.html" %}
{% block page %}
{% load staticfiles %}

<div class="container-fluid" style="background:white; padding-top:75px;">
  {% comment %}<div class="row">
    <div class="col-md-offset-3 col-md-6 col-xs-12">
      <h1 style="text-align:center"> Welcome to Tutor Chat! </h1>
    </div>
  </div>{% endcomment %}
  
  <div class="row">
    <div class="col-md-12 col-xs-12">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <span class="glyphicon glyphicon-comment"></span> Tutor Chat
           {% if isTutor %}
                <a class="btn btn-danger pull-right" style="margin-top: -7px;" href="{% url 'ta_tutor:ta_tutor' %}"> End Session </a>
            {% else %}
                <a class="btn btn-danger pull-right" style="margin-top: -7px;" href="{% url 'student:student' %}"> End Session </a>
            {% endif %}
        </div>
        <div class="panel-body" id="chatbody" style="max-height:450px; min-height:450px; overflow-y: scroll;">
          <table id="chat">
            <!-- Chat messages appear here -->
          </table>
        </div>
        <div class="panel-footer">
          <form id="chatform">
            <input id="message" type="text" style="width:80%" placeholder="Press Enter to Send" autocomplete="off">
            <button class="btn btn-primary" type="submit">Send</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>



<!-- EXAMPLE CHAT PANEL -->
<!--<div class="container-fluid">
    <div class="row">
        <div class="col-md-12" style="width:100%;">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-comment"></span> Tutor Chat
                </div>

                <div class="panel-body">
                    <ul class="chat">
                        <li class="left clearfix"><span class="chat-img pull-left">
                            <img src="http://placehold.it/50/55C1E7/fff&text=U" alt="User Avatar" class="img-circle" />
                        </span>
                            <div class="chat-body clearfix">
                                <div class="header">
                                    <strong class="primary-font">Jack Sparrow</strong> <small class="pull-right text-muted">
                                        <span class="glyphicon glyphicon-time"></span>12 mins ago</small>
                                </div>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare
                                    dolor, quis ullamcorper ligula sodales.
                                </p>
                            </div>
                        </li>
                        <li class="right clearfix"><span class="chat-img pull-right">
                            <img src="http://placehold.it/50/FA6F57/fff&text=ME" alt="User Avatar" class="img-circle" />
                        </span>
                            <div class="chat-body clearfix">
                                <div class="header">
                                    <small class=" text-muted"><span class="glyphicon glyphicon-time"></span>13 mins ago</small>
                                    <strong class="pull-right primary-font">Bhaumik Patel</strong>
                                </div>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare
                                    dolor, quis ullamcorper ligula sodales.
                                </p>
                            </div>
                        </li>
                        <li class="left clearfix"><span class="chat-img pull-left">
                            <img src="http://placehold.it/50/55C1E7/fff&text=U" alt="User Avatar" class="img-circle" />
                        </span>
                            <div class="chat-body clearfix">
                                <div class="header">
                                    <strong class="primary-font">Jack Sparrow</strong> <small class="pull-right text-muted">
                                        <span class="glyphicon glyphicon-time"></span>14 mins ago</small>
                                </div>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare
                                    dolor, quis ullamcorper ligula sodales.
                                </p>
                            </div>
                        </li>
                        <li class="right clearfix"><span class="chat-img pull-right">
                            <img src="http://placehold.it/50/FA6F57/fff&text=ME" alt="User Avatar" class="img-circle" />
                        </span>
                            <div class="chat-body clearfix">
                                <div class="header">
                                    <small class=" text-muted"><span class="glyphicon glyphicon-time"></span>15 mins ago</small>
                                    <strong class="pull-right primary-font">Bhaumik Patel</strong>
                                </div>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare
                                    dolor, quis ullamcorper ligula sodales.
                                </p>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="panel-footer">
                    <div class="input-group">
                        <input id="btn-input" type="text" class="form-control input-sm" placeholder="Type your message here..." />
                        <span class="input-group-btn">
                            <button class="btn btn-warning btn-sm" id="btn-chat">
                                Send</button>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>-->

<script type="text/javascript" src='{% static "js/reconnecting-websocket.min.js" %}'></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
<script type="text/javascript" src='{% static "js/messenger.js" %}'></script>
{% endblock page %}