tutorlab/tutorlab/home/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^login/$', views.submit_login, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'schedule/$', views.ta_schedule, name='schedule'),
    url(r'^pusher_authenticate/$', views.pusher_authentication, name='auth'),
    url(r'^admin_import/$', views.admin_import, name='admin_import'),
    url(r'^admin_purge/$', views.admin_purge, name='admin_purge'),
    url(r'^admin_manage/$', views.admin_manage, name='admin_manage')
]

tutorlab/tutorlab/student/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'student'
urlpatterns = [
   url(r'^$', views.student, name='student'),
   url(r'activate-student/(?P<token>[\w:-]+)$', views.activateStudent, name='activate_student'),
   url(r'confirm-appt/$', views.confirmAppt, name='confirm_appt'),
   url(r'create-appt/$', views.createAppt, name='create_appt'),
   url(r'create-student/$', views.createStudent, name='create_student'),
   url(r'delete-appt/$', views.deleteAppt, name='delete_appt'),
   url(r'delete-event/$', views.deleteEvent, name='delete_event'),
   url(r'request-new-tutor/$', views.newTutor, name='new_tutor'),
   url(r'api/cancel-request/$', views.cancelRequest, name='cancel_request'),
   url(r'api/delete-survey/$', views.deleteSurvey, name='delete_survey'),
   url(r'api/get-classes/$', views.getClasses, name='get_classes'),
   url(r'api/get-issue-list/$', views.getIssues, name='get_issues'),
   url(r'api/post-request/$', views.postRequest, name='post_request'),
   url(r'api/submit-survey/$', views.submitSurvey, name='submit_survey'),
]
 

tutorlab/tutorlab/tutorlab/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^', include('home.urls')),
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^student/', include('student.urls')),
    url(r'^instructor/', include('instructor.urls')),
    url(r'^ta_tutor/',include('ta_tutor.urls')),
    url(r'^tutor_admin/', include('tutor_admin.urls')),
    url(r'^survey/', include('survey.urls')),
    url(r'^password_reset/',include('password_reset.urls')),
    url(r'^msg/',include('messenger.urls')),
    url(r'^forum/', include('forum.urls')),
]

#if settings.DEBUG:
#    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutorlab/tutorlab/home/models.py
from django.db import models

# Create your models here.
class App_Course(models.Model):
    course_name = models.CharField(max_length = 40)
    course_number = models.IntegerField(default = 0)
    course_section = models.IntegerField(default = 0)

    def __str__(self):
        return self.course_name

class CommonStudentIssue(models.Model):
    issue = models.CharField(max_length = 150)

    def __str__(self):
        return self.issue

tutorlab/tutorlab/home/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from django.core.exceptions import ObjectDoesNotExist

from datetime import datetime
try:
    from django.contrib.sites.shortcuts import get_current_site
except ImportError:
    from django.contrib.sites.models import get_current_site
from django.core import signing
from django.core.files.storage import FileSystemStorage
from django.core.mail import send_mail
from django.core.validators import validate_email
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.template import loader
from django.views.decorators.csrf import csrf_exempt

from .models import App_Course
from instructor.models import Instructor, Course, Student
from tutor_admin.models import Term
from ta_tutor.models import Session
from survey.models import Survey
from student.models import Student as StudentAccount

from pusher import Pusher, pusher
import codecs, json, sys, pyexcel as pe
from collections import defaultdict
from xlrd import XLRDError

# LOAD HOME PAGE
def index(request):
    return render(request, 'home/home.html')

# CONTACT US PAGE
def contact(request):
    context = {
        'contact': ['Email: UtsaTutorLab@gmail.com'],
        'title': "Contact Us",
    }
    return render(request, 'home/contact.html', context)

# LOGIN USER, REDIRECT TO THEIR PROFILE
def submit_login(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            if user.groups.filter(name='Student').exists():
                return HttpResponse(
                    json.dumps("/student"),
                    content_type="application/json"
                )
            if user.groups.filter(name='Tutor').exists():
                return HttpResponse(
                    json.dumps("/ta_tutor"),
                    content_type="application/json"
                )
            if user.groups.filter(name='Tutor_Admin').exists():
                return HttpResponse(
                    json.dumps("/tutor_admin"),
                    content_type="application/json"
                )
            if user.groups.filter(name='Instructor').exists():
                return HttpResponse(
                    json.dumps("/instructor"),
                    content_type="application/json"
                )
            if username == 'admin' or username == 'bifrost_larry':
                return HttpResponse(
                    json.dumps("/admin"),
                    content_type="application/json"
                )
        else:
            return HttpResponse(
                json.dumps("false-1"),
                content_type="application/json"
            )
    else:
        return HttpResponse(
            json.dumps("false-2"),
            content_type="application/json"
        )

# LOGOUT USER
def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

# REDIRECT TO USER PROFILE
def profile(request):
    user = request.user
    if user is not None:
        if user.is_active:
            if user.groups.filter(name='Student').exists():
                return HttpResponseRedirect('/../student/')
            if user.groups.filter(name='Tutor').exists():
                return HttpResponseRedirect('/../ta_tutor/')
            if user.groups.filter(name='Instructor').exists():
                return HttpResponseRedirect('/../instructor/')
            if user.groups.filter(name='Tutor_Admin').exists():
                return HttpResponseRedirect('/../instructor/')
            if user.username == 'admin' or  user.username == 'bifrost_larry':
                return HttpResponseRedirect('/../admin/')
        else:
            return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/')

@csrf_exempt
def pusher_authentication(request):
	pusher_client = pusher.Pusher(app_id=settings.PUSHER_APP_ID,key=settings.PUSHER_KEY,secret=settings.PUSHER_SECRET)
	pusher_client.trigger(u'ch1',u'enqueue',{})	

	return HttpResponse("Ooh secret")

# SHOWS ALL TUTORS SCHEDULES
def ta_schedule(request):
    context = {
        'title': "Tutor Schedule",
    }
    return render(request, 'home/schedule.html', context)




@login_required(login_url='/admin/')
def admin_import(request):
    if request.user.is_active:
        if not request.user.is_superuser:
            return HttpResponseRedirect('/profile')
        if request.method == "GET":
            return render(request, "home/admin_import.html")
        if request.method == "POST" and request.FILES['file']:
            xlsFile = request.FILES['file']
            i_first_name = i_last_name = i_user_name = i_email = class_name = class_num = s_first_name = s_last_name = s_user_name = ' '
            num_i = num_c = num_s = 0
            try:
                fs = FileSystemStorage()
                filename = fs.save(xlsFile.name, xlsFile)
                print("File name =", xlsFile)
                sheet = pe.get_sheet(file_name=fs.path(xlsFile.name), name_columns_by_row=0)
                records = sheet.to_records()
                for record in records:
                    keys = sorted(record.keys())
                    for key in keys:
                        if key == "Instructor First Name":
                            print(str(record[key]))
                            i_first_name = record[key]
                        elif key == "Instructor Last Name": 
                            print(str(record[key]))
                            i_last_name = record[key]
                        elif key == "Instructor Username": 
                            print(str(record[key]))
                            i_user_name = record[key]
                        elif key == "Instructor Email":
                            print(str(record[key]))
                            i_email = record[key]
                        elif key == "Class Name":
                            print(str(record[key]))
                            class_name = record[key]
                        elif key == "Class Number":
                            print(str(record[key]))
                            class_num = record[key]
                        elif key == "Student abc123":
                            print(str(record[key]))
                            s_user_name = record[key]
                        elif key == "Student First Name":
                            print(str(record[key]))
                            s_first_name = record[key]
                        elif key == "Student Last Name":
                            print(str(record[key]))
                            s_last_name = record[key]

                    # Get or create user
                    user, user_created = User.objects.get_or_create(username=i_user_name, first_name=i_first_name, last_name=i_last_name, email=i_email)
                    group = Group.objects.get(name='Instructor')
                    group.user_set.add(user)
                    # Get or create current instructor
                    cur_instructor,created = Instructor.objects.get_or_create(user=user, first_name=i_first_name, last_name=i_last_name, email=i_email)
                    cur_instructor.save()

                    if(user_created):
                        # send email to setup password
                        send_activation(request, user.username, user.email)
                        num_i+=1

                    # Get or create current course and associate with instructor
                    cur_course, course_created = Course.objects.get_or_create(course_num=class_num, course_name=class_name)
                    cur_course.save()
                    cur_course.Instructor = cur_instructor
                    cur_course.save()
                    if(course_created):
                         num_c+=1                    
                    
                    # Get or create current student and associate with course
                    cur_student, student_created = Student.objects.get_or_create(first_name=s_first_name, last_name=s_last_name, studentID=s_user_name)
                    cur_student.save()
                    cur_student.courses.add(cur_course)
                    cur_student.save()
                    if(student_created):
                        num_s+=1
        
                fs.delete(xlsFile.name)
                data = {
                    "bool":"true",
		    "i_created":num_i,
                    "c_created":num_c,
                    "s_created":num_s
                }
                return HttpResponse(
                    json.dumps(data),
                    content_type="application/json"
                )


            except XLRDError:
                print("xlrd error")
                lastCol = firstCol = userCol = 0
                i_last_name = i_first_name = i_email = class_name = class_num = s_first_name = s_last_name = s_user_name = ""
                fs = FileSystemStorage()
                filename = fs.save(xlsFile.name, xlsFile)
                with codecs.open(fs.path(xlsFile.name), encoding='UTF-16') as f:
                    for rowx, row in enumerate(f):
                        if row.endswith(u'\r\n'): row = row[:-2]
                        data = row.split(u'\t ,')
                        for colx, datum in enumerate(data):
                            info = datum.strip("'\"")
                            if(rowx == 0):
                                if( info == 'Instructor First Name'):
                                    print(info)
                                    iFirstCol = colx

tutorlab/tutorlab/home/templates/home/includes/footer.html
{% load staticfiles %}
{% block footer %}
    <footer class="site-footer">
        <div>
            <p style="color:white">CS Department Tutorlab</p>
        </div>
    </footer>
{% endblock %}

tutorlab/tutorlab/home/templates/home/includes/header.html
{% load staticfiles %}
{% block header %}
<nav class="navbar navbar-inverse navbar-fixed-top" id="header_bar">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      {% if user.is_authenticated %}
      <a class="navbar-brand" id="navbar-tutorlab" href="{% url 'home:home' %}">TutorLab(</a>
      <a class="navbar-brand" id="navbar-username" href="{% url 'home:profile' %}">{{ user.username }}<p style="display:inline; color:white;"> )</p></a>
      {% else %}
      <a class="navbar-brand" id="navbar-tutorlab" href="/">TutorLab( )</a>
      {% endif %}
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav" style="font-size:16px;">
        <li><a href="{% url 'home:contact' %}">Contact</a></li>
        <li><a href="{% url 'home:schedule' %}">Tutors Schedule</a></li>
      </ul>
<!-- this will make the login only visiable on the home page -->
      {% if user.is_authenticated  %} 
      <form action="{% url 'home:logout' %}" class="navbar-form navbar-right" style="padding-left:30px;">
          <button type="submit" class="btn btn-warning">Logout</button>
      </form>
      {% else %}
<!-- NEW MODAL LOGIN -->
      <ul class="nav navbar-nav navbar-right" style="padding:8px;">
        <li><button href="#" class="btn btn-primary" data-toggle="modal" data-target="#login_modal">Login</li>
      </ul>
      {% endif %}
    </div>
  </div>
</nav>    
{% endblock %}

tutorlab/tutorlab/home/templates/home/includes/modal.html
{% block modal %}
<!-- Modals -->
    <div class="modal fade" id="login_modal" role="dialog" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog modal-sm">
          <form action="{% url 'home:login' %}" method='post' id="login-form"> 
            {% csrf_token %}
            <div class="modal-content">
              <div class="modal-header">
                <h2 class="modal-title text-center">Login</h2>
              </div>
              <div class="modal-body">
                <div class="alert alert-danger" id="invalid-login" role="alert" style=" display:none; margin-bottom: 5px;"></div>
                <div class="form-group">
                  <label>Username</label>
                  <input type="text" name='username' id="username" class="form-control">
                </div>
                <div class="form-group">
                  <label>Password</label>
                  <a style="font-size:12px; display:inline;" href='{% url "password_reset_recover" %}'>Forgot Password?</a>
                  <input type="password" name='password' id="password" class="form-control">
                </div>  
                <button type="submit" class="btn btn-success btn-block">Login</button> 
              </div>
              <div class="modal-footer" style="text-align:center;">
                <label>New to TutorLab?</label>
                <a style="font-size:12px;" href='{% url "student:create_student" %}'> Create Account </a>    
              </div>
            </div>
          </form>
        </div>
    </div>
{% endblock %}